### ISSUE TITLE
Segfault with go-get installed awsweb

### ISSUE THREAD

**Issue by brainstorm** [glassechidna/awsweb#16] opened 2018-02-15 23:40 UTC
I installed `awsweb` via `go get github.com/glassechidna/awsweb` instead of using the binary releases and I got this in return:

```
$ awsweb browser mycompany-prod
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x14b930f]

goroutine 1 [running]:
github.com/glassechidna/awsweb/cmd.doBrowser(0x1884040, 0xc4201a4b70, 0x0, 0x0, 0x7fff5fbff31f, 0xe)
	/Users/romanvg/go/src/github.com/glassechidna/awsweb/cmd/browser.go:69 +0x6f
github.com/glassechidna/awsweb/cmd.init.0.func1(0xc420190c80, 0xc420045420, 0x1, 0x1)
	/Users/romanvg/go/src/github.com/glassechidna/awsweb/cmd/browser.go:43 +0x9e
github.com/spf13/cobra.(*Command).execute(0xc420190c80, 0xc4200453e0, 0x1, 0x1, 0xc420190c80, 0xc4200453e0)
	/Users/romanvg/go/src/github.com/spf13/cobra/command.go:757 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0x18ba280, 0x18ba4e0, 0xc420157f48, 0xc420157f50)
	/Users/romanvg/go/src/github.com/spf13/cobra/command.go:843 +0x334
github.com/spf13/cobra.(*Command).Execute(0x18ba280, 0x0, 0xc420157f48)
	/Users/romanvg/go/src/github.com/spf13/cobra/command.go:791 +0x2b
github.com/glassechidna/awsweb/cmd.Execute()
	/Users/romanvg/go/src/github.com/glassechidna/awsweb/cmd/root.go:40 +0x31
main.main()
	/Users/romanvg/go/src/github.com/glassechidna/awsweb/main.go:20 +0x20
```

I'm running `go 1.9.4`, brew-installed today.

**Comment by aidansteele** [comment] 2018-08-13 23:11
Hi. I know it's probably much too late, but I am *so sorry* for the delayed response. I need to check my GitHub settings as I didn't get any notification about this issue. 😕 

The issue is now fixed as of https://github.com/glassechidna/awsweb/commit/0cc582edaaaae92930038409ada354dd6d4a850e (build 0.1.2)

**Closed as completed by aidansteele** 2018-08-13 23:11 UTC
